### PR TITLE
internal lb fix (counts from 1

### PR DESCRIPTION
**Pull request by johnnyrun**
Schermata 2020-12-29 alle 22 09 10
Hi.
Thanks for writing this tool.

I can't get the name from internal loadbalancer because prefixed.

### CODE REVIEW

**Comment by oxyno-zeta** [comment]
Hello !

Happy to see that this can help other people too !

I see the problem. You are right.

Can you update your PR with the following points please ?

- [x] Rewrite commits using the angular commit convention (Yours should be something like: `fix(aws): Fix internal load balancer prefix case`
- [x] Add unit test

Thanks !

**Comment by johnnyrun** [comment]
two horrible force push... but now it should be fine.

O found that test uses old short ids.. but it is another story.

**Comment by oxyno-zeta** [comment]
No problem for force push. You are not the only one :smile: .

Thanks for the update :+1: ! This is a good fix.

I will merge it and release.


For the short ids, as the algorithm isn't matching a length, there is no problem with this of the moment I think.

**Comment by oxyno-zeta** [comment]
Release 1.2.2 is done. You have been mentionned in the changelog for your work. Thanks !

**Pull request merged**
